package com.jathursh.spring_boot_crud.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;  /*@AllArgsConstructor and @NoArgsConstructor are Lombok
                                     annotations that can be used to automatically generate
                                     constructors for Java classes.*/
import lombok.Data;  /*Lombok is a Java library that can help to reduce boilerplate code
                       in Java classes. It provides a set of annotations that can be used
                       to automatically generate methods such as getters, setters, equals,
                       hashCode, and toString, as well as constructors and builders.*/
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "CUSTOMER")

public class Customer {

    @Id
    @GeneratedValue  // autogenerated value given by hibernate
    private int id;
    private String name;
    private String email;
    private String address;
}
